### ISSUE TITLE
Demo problem

### ISSUE THREAD

**Issue by valerio-bozzolan** [nerik/leaflet-graphicscale#10]
Hi all! The plugin is very nice but I noticed that the tileserver in the demo has problems since I see a gray screen.

Maybe we can just adopt the default OpenStreetMap tileserver and support HTTPs as well:

* https://nerik.github.io/leaflet-graphicscale/demo/

What do you think about? :)

**Comment by claustres** [comment]
In any case it helps we started this fork https://github.com/kalisio/leaflet-graphicscale to keep it alive, the demo relies on OSM server.
