### ISSUE TITLE
Animation direction should hang on control position

### ISSUE THREAD

**Issue by AbelVM** [nerik/leaflet-graphicscale#3]
So:
- The control is *left -> animation left to right;
- The control is *right -> animation right to left.

(Good work! I really like this scale)

**Comment by nerik** [comment]
Thanks for the report. I don't see how I could implement that while keeping the code simple and clean enough, so I won't fix for now. 
You are more than welcome to suggest a way to do this in a PR if you feel like it.

**Comment by AbelVM** [comment]
I'm already using your scale in prod, so I'm very interested in improve it. As soon as I have some time to dive deeper in your code, I will try to pull some stuff for animations

**Comment by nerik** [comment]
I'd be interested to see how you use it :)
