### ISSUE TITLE
How to use with Miles and inches instead of Km and m?

### ISSUE THREAD

**Issue by mehany** [nerik/leaflet-graphicscale#5]
I can tell from the source code that the code handles only Km and meters but is there a way that I can get this to work with Miles instead?

**Comment by nerik** [comment]
The lib was designed to handle metric system units only, as I had no need for another measurement system (yet).
It would be reasonably easy to implement though, any PR is welcome :)

**Comment by mehany** [comment]
@nerik if you point me to the right direction ( the pieces of the code that I should add ), I would do it and I will do the PR once completed. I tried already to implement it but things seem to be strongly tied together ( Css, units and the math in between ).

**Comment by nerik** [comment]
So I'm having a look at this code I wrote 1 year ago (facepalm) and actually it's not gonna be that easy, because it assumes that going from one unit to one another is done using [powers of 10](https://github.com/nerik/leaflet-graphicscale/blob/master/src/Leaflet.GraphicScale.js#L275), which won't work with miles/feet.
Because the lib doesn't have tests (2nd facepalm), it doesn't feel great hacking around the problem - I'll try to have a look this weekend and rewrite the important bits.
Sorry.

**Comment by mehany** [comment]
@nerik at least you are giving it an honest try, I am happy to contribute.

**Comment by brianreavis** [comment]
@nerik I took a stab at this. The computation is a little more configurable via lookup table (of sorts) that allows people to granularly control what sort of divisions feel most natural. It also lets you control what's allowed to be subdivided, and the value to be subdivided. This implementation is more susceptible to "holes" than yours, however. If the table's not exhaustive, you'll end up with nothing that fits in `maxUnitsWidth` and it'll hide the scale. I haven't had any trouble with that though.  Give it a shot and, if you're interested, I can try to document / clean it up a little / put out a pull request. And if not, I understand :)

https://github.com/naturalatlas/leaflet-graphicscale/commit/91878d2ca1b07b6233bd5c2d6f683fc305607f95

Awesome component, by the way!

**Comment by nerik** [comment]
Hi Brian,
Thanks. I have a sporadic access to a computer atm, but I'll definitely have a look.
Natural Atlas is a terrific project, congrats!

**Comment by claustres** [comment]
In any case it helps we started this fork https://github.com/kalisio/leaflet-graphicscale to keep it alive. We kept the original code but made it handle multiple unit systems simply by letting the library be aware of the right conversion factor to use between meters and the target unit.

**Comment by nerik** [comment]
Hello @claustres, unfortunately, I don't have time to maintain this lib anymore (and I haven't been using Leaflet for years now). Would you be interested in taking ownership of this repo?

**Comment by claustres** [comment]
Hi @nerik and thanks for your previous work. I've started a fork in our own organisation to make it easier to manage so I don't think it is useful to take ownership of your repo. However, maybe you could add a link on the top of the README to this new maintained fork.

**Comment by nerik** [comment]
Done: https://github.com/nerik/leaflet-graphicscale/commit/2d0595be3fc1ef97edbeacba273d5cc1b558eb48

I'll also archive this repo.
