### ISSUE TITLE
Smaller units

### ISSUE THREAD

**Issue by semeleven** [nerik/leaflet-graphicscale#7]
If a large scale at the map, the line is not reduced to smaller units than 4 meters. How i can fix it?
![Image](https://downloader.disk.yandex.ru/disk/e0ae49cb147a742d188cab493b820cf79a151b31e0ee44492075cf1de45d0904/57d70fb1/TKdgbElyDL5rBJ5Q9aNKC6BRFReBeQUFGXSg9g7RDt7gd_S71osYwY335NLmxW4HqI-qxK8nnDrjvrQrKHcgCA%3D%3D?uid=0&filename=2016-09-12_19-25-16.png&disposition=attachment&hash=veDRd5h8no8/jkV4iYj%2BHsgOmiEh0ugeBnY2UqihPfw%3D&limit=0&content_type=image%2Fpng&fsize=3283&hid=3a84c52cfa050b83fff5da1b001eb876&media_type=image&tknv=v2)

**Comment by rpopiolek** [comment]
Hi - I struggle with the same issue - is there an idea to fix it - we have maps with max-zoom 25/26

**Comment by nerik** [comment]
Please re-open here if still applicable: https://github.com/kalisio/leaflet-graphicscale/issues
